import type { FixtureKind, RoomDef, SystemId } from "./types";

type Raw = [
  id: string,
  name: string,
  span: number,
  fixture: FixtureKind,
  systems: SystemId[],
  purpose: string,
  metric: [label: string, base: number, unit: string],
  why: string,
];

const RAW: Record<number, Raw[]> = {
  1: [
    ["f1-entrance", "Main Entrance", 1.2, "generic", ["people", "comms"],
      "Controlled surface access point where arrivals are logged before entering the shelter.",
      ["Access cycles / day", 14, ""],
      "A single, supervised doorway keeps the protected volume separate from whatever is happening outside."],
    ["f1-exit", "Emergency Exit Access", 0.9, "generic", ["people"],
      "Secondary protected route to the surface for evacuation or rescue.",
      ["Clearance", 100, "%"],
      "A second way out means one blocked corridor never traps the whole community."],
    ["f1-gear", "Safety Gear & Equipment", 1, "lockers", ["people"],
      "Storage for protective suits, respirators, lights and personal safety gear.",
      ["Kits ready", 30, ""],
      "Equipment only helps if it is staged where people pass through."],
    ["f1-decon-a", "Decontamination A", 1, "shower", ["water", "air"],
      "First wash-down and air-shower bay for people returning from the surface.",
      ["Cycle time", 8, "min"],
      "Contaminants stopped at the door never reach the living floors."],
    ["f1-decon-b", "Decontamination B", 1, "shower", ["water", "air"],
      "Parallel decontamination bay so groups can be processed without queuing.",
      ["Cycle time", 8, "min"],
      "Redundant paths keep the entry from becoming a bottleneck in a crisis."],
    ["f1-generator", "Generator Room", 1.2, "machines", ["power"],
      "Primary generators supporting the shelter alongside surface solar collection.",
      ["Output", 82, "%"],
      "Every other system on this list stops without a reliable electrical supply."],
    ["f1-reception", "Reception / Check-in", 1.1, "desks", ["people", "comms"],
      "Registration desk where residents and visitors are accounted for.",
      ["Accounted for", 24, "people"],
      "Knowing exactly who is inside is the first step of any emergency response."],
    ["f1-storage", "Emergency Equipment Storage", 1.1, "lockers", ["people"],
      "Staged stretchers, tools, spare filters and rapid-response supplies.",
      ["Stock level", 88, "%"],
      "Response speed depends on supplies being pre-positioned, not searched for."],
  ],
  2: [
    ["f2-control", "Security / Control Room", 1.3, "screens", ["comms", "power"],
      "Central operations desk overseeing access, alarms and facility status.",
      ["Systems watched", 42, ""],
      "One place where the whole facility can be seen makes coordinated decisions possible."],
    ["f2-fire", "Fire-Control Room", 1.1, "screens", ["comms", "water"],
      "Monitoring point for detection, suppression zones and pump status.",
      ["Zones monitored", 30, ""],
      "Fire underground is a shared risk, so detection is a community-wide service."],
    ["f2-obs-a", "Observation A", 0.9, "seats", ["comms", "people"],
      "Quiet observation and de-escalation space for wellbeing or safety concerns.",
      ["Capacity", 2, "people"],
      "Conceptual space showing that safety planning also means caring for people."],
    ["f2-obs-b", "Observation B", 0.9, "seats", ["comms", "people"],
      "Second observation space so situations can be separated calmly.",
      ["Capacity", 2, "people"],
      "Separating a situation is often enough to resolve it peacefully."],
    ["f2-cctv", "CCTV Monitoring", 1.1, "screens", ["comms", "power"],
      "Camera feeds covering entries, corridors and technical spaces.",
      ["Cameras online", 36, ""],
      "Awareness of shared spaces protects equipment everyone depends on."],
    ["f2-comms", "Emergency Communications", 1.2, "screens", ["comms", "power"],
      "Radio and network links to the surface and between floors.",
      ["Link quality", 94, "%"],
      "Isolation is dangerous; communication turns a bunker into part of a wider network."],
    ["f2-vault", "Controlled Equipment Vault", 1, "lockers", ["comms"],
      "Restricted storage for sensitive equipment, logged and access-controlled.",
      ["Access log", 100, "%"],
      "Conceptual model of accountability: restricted items are tracked, not hidden."],
    ["f2-training", "Controlled Training Area", 1.1, "generic", ["people"],
      "Supervised space for drills such as evacuation and emergency procedures.",
      ["Drills / month", 4, ""],
      "Practised routines are what make emergency plans work under stress."],
  ],
  3: [
    ["f3-water-system", "Water System", 1.1, "pumps", ["water", "power"],
      "Distribution manifolds and pumps that move water through the whole shelter.",
      ["Pressure", 92, "%"],
      "Water is the system with the most downstream dependants in the facility."],
    ["f3-treatment", "Water Treatment", 1.1, "tanks", ["water", "power"],
      "Filtration and disinfection stages producing potable water.",
      ["Throughput", 90, "%"],
      "Treating water locally turns a finite store into a renewable loop."],
    ["f3-storage", "Water Storage Connection", 1, "tanks", ["water"],
      "Buffer reservoirs linking collection, treatment and distribution.",
      ["Reserve", 87, "%"],
      "Storage is what absorbs the gap between supply interruptions and demand."],
    ["f3-air-filter", "Air Filtration", 1.1, "machines", ["air", "power"],
      "Multi-stage filters conditioning intake and recirculated air.",
      ["Filter life", 78, "%"],
      "Air quality is the fastest constraint underground — minutes, not days."],
    ["f3-hvac", "HVAC Equipment", 1.1, "machines", ["air", "power"],
      "Fans, heat exchange and duct control keeping every floor ventilated.",
      ["Circulation", 96, "%"],
      "Filtered air still has to reach people, which is what circulation provides."],
    ["f3-pump-a", "Fire-Control Pump A", 0.85, "pumps", ["water", "power"],
      "Pressurised supply for suppression systems across the shelter.",
      ["Standby pressure", 95, "%"],
      "Standby capacity is idle until the one moment it matters."],
    ["f3-pump-b", "Fire-Control Pump B", 0.85, "pumps", ["water", "power"],
      "Redundant suppression pump on an independent supply.",
      ["Standby pressure", 95, "%"],
      "Critical safety systems are duplicated so a single failure is survivable."],
    ["f3-fiber", "Fiber-Optic / Server Room", 1.1, "servers", ["comms", "power", "air"],
      "Network core linking sensors, cameras and floor controllers.",
      ["Uptime", 99, "%"],
      "Sensor data is how a small community manages a large facility."],
    ["f3-database", "Computer Database", 1, "servers", ["comms", "power"],
      "Records for inventory, maintenance, health logs and education material.",
      ["Records", 96, "%"],
      "Knowledge stored locally keeps working when outside networks do not."],
    ["f3-maintenance", "Maintenance Tools & Materials", 1, "lockers", ["power"],
      "Spares, tools and consumables for repairing the technical floors.",
      ["Spares", 84, "%"],
      "Nothing here lasts for months without the ability to repair it."],
  ],
  4: [
    ["f4-research", "Research / Diagnostic Room", 1.05, "cabinets", ["medical", "power"],
      "Sample analysis and diagnostic equipment supporting the care team.",
      ["Capacity", 88, "%"],
      "Understanding a health problem early keeps it from spreading through a closed community."],
    ["f4-obgyn", "OB-GYN", 1, "medbed", ["medical", "water"],
      "Maternal and reproductive health care space.",
      ["Readiness", 92, "%"],
      "A community that plans for years must plan for new life, not only survival."],
    ["f4-dental", "Dental", 0.95, "medbed", ["medical", "water", "power"],
      "Dental care and hygiene treatment space.",
      ["Readiness", 90, "%"],
      "Untreated everyday problems become emergencies when no outside help exists."],
    ["f4-operating", "Operating / Treatment Room", 1.2, "medbed", ["medical", "power", "air"],
      "Sterile-controlled room for procedures and urgent treatment.",
      ["Readiness", 94, "%"],
      "This room is the clearest example of medicine depending on power and clean air."],
    ["f4-iso-a", "Isolation A", 0.8, "medbed", ["medical", "air"],
      "Separately ventilated room for infectious or immune-vulnerable patients.",
      ["Occupancy", 0, "beds"],
      "In a sealed community, isolation capacity protects everyone at once."],
    ["f4-iso-b", "Isolation B", 0.8, "medbed", ["medical", "air"],
      "Second isolation room allowing separation of different cases.",
      ["Occupancy", 0, "beds"],
      "Two separate cases must never be forced to share one room."],
    ["f4-iso-c", "Isolation C", 0.8, "medbed", ["medical", "air"],
      "Reserve isolation room held for surge situations.",
      ["Occupancy", 0, "beds"],
      "Surge capacity is planned before it is needed, never during."],
    ["f4-equipment", "Medical Equipment", 1, "cabinets", ["medical", "power"],
      "Monitors, oxygen support and powered devices used across the floor.",
      ["Serviceable", 91, "%"],
      "Medical equipment is the most power-sensitive load in the shelter."],
    ["f4-pharmacy", "Pharmacy", 1, "cabinets", ["medical", "power"],
      "Climate-controlled medicine and consumable storage.",
      ["Stock", 91, "%"],
      "Supplies deplete steadily and cannot be restocked from outside."],
    ["f4-comfort", "Comfort Room", 0.85, "seats", ["water", "people"],
      "Sanitary and recovery space attached to the medical floor.",
      ["Availability", 100, "%"],
      "Dignity and hygiene are part of health care, not extras."],
    ["f4-counseling", "Counseling Room", 0.95, "seats", ["people", "medical"],
      "Private space for mental-health and emotional support.",
      ["Sessions / week", 9, ""],
      "Long confinement makes psychological care as essential as physical care."],
  ],
  5: [
    ["f5-aquaponics", "Aquaponics", 1.4, "tanks", ["food", "water", "power"],
      "Fish tanks paired with grow beds, where fish nutrients feed the plants.",
      ["Yield", 76, "%"],
      "One loop producing protein and vegetables from the same water is the core of the food plan."],
    ["f5-hydroponics", "Hydroponics / Agriculture", 1.5, "plants", ["food", "water", "power"],
      "Stacked soil-free grow racks under tuned lighting.",
      ["Yield", 74, "%"],
      "Vertical growing turns limited floor area into continuous harvests."],
    ["f5-poultry", "Poultry Area", 1.1, "plants", ["food", "air", "waste"],
      "Small managed flock for eggs, separately ventilated.",
      ["Flock health", 88, "%"],
      "Diverse food sources make the community less fragile to a single crop failure."],
    ["f5-food-storage", "Food Storage", 1.1, "cabinets", ["food", "power"],
      "Cooled and dry bulk storage of harvested and preserved food.",
      ["Capacity used", 72, "%"],
      "Storage smooths the gap between harvest cycles and daily meals."],
    ["f5-pantry", "Food Pantry", 1, "cabinets", ["food"],
      "Working stock issued to the kitchen on Floor 8.",
      ["Days on hand", 40, "days"],
      "Rationing is only fair when stock levels are visible to everyone."],
    ["f5-seed", "Seed Storage", 0.9, "cabinets", ["food"],
      "Protected seed bank for future planting cycles.",
      ["Varieties", 64, ""],
      "Seeds are the difference between eating stored food and growing more."],
    ["f5-air", "Supporting Air Filtration", 1, "machines", ["air", "power"],
      "Dedicated filtration balancing humidity and CO₂ on the growing floor.",
      ["Balance", 93, "%"],
      "Plants and people compete for the same air, so this floor is tuned separately."],
  ],
  6: [
    ["f6-b1", "Bedroom 1", 0.8, "bunks", ["people", "air"], "Private quarters for a resident or family unit.", ["Occupancy", 2, "people"], "Personal space is what keeps months of shared living bearable."],
    ["f6-b2", "Bedroom 2", 0.8, "bunks", ["people", "air"], "Private quarters with personal storage.", ["Occupancy", 2, "people"], "Privacy reduces conflict in a closed community."],
    ["f6-b3", "Bedroom 3", 0.8, "bunks", ["people", "air"], "Private quarters with personal storage.", ["Occupancy", 2, "people"], "Rest quality directly affects health and morale."],
    ["f6-b4", "Bedroom 4", 0.8, "bunks", ["people", "air"], "Private quarters with personal storage.", ["Occupancy", 1, "people"], "Flexible room sizing supports different household types."],
    ["f6-b5", "Bedroom 5", 0.8, "bunks", ["people", "air"], "Private quarters with personal storage.", ["Occupancy", 2, "people"], "Predictable sleep cycles matter when there is no daylight."],
    ["f6-b6", "Bedroom 6", 0.8, "bunks", ["people", "air"], "Private quarters with personal storage.", ["Occupancy", 2, "people"], "Quiet zones are separated from community noise by design."],
    ["f6-b7", "Bedroom 7", 0.8, "bunks", ["people", "air"], "Private quarters with personal storage.", ["Occupancy", 1, "people"], "Spare capacity allows for guests and reassignment."],
    ["f6-b8", "Bedroom 8", 0.8, "bunks", ["people", "air"], "Private quarters with personal storage.", ["Occupancy", 2, "people"], "Room-by-room accounting keeps headcounts accurate."],
    ["f6-laundry", "Laundry", 1, "machines", ["water", "power"], "Shared washing facilities using recycled greywater.", ["Loads / day", 6, ""], "Clean clothing is basic disease prevention."],
    ["f6-bath", "Shared Bathrooms", 1.1, "shower", ["water", "waste"], "Shared sanitary block serving the residential floor.", ["Availability", 100, "%"], "Sanitation links directly to Floor 10 treatment."],
    ["f6-store", "Personal Storage", 0.9, "lockers", ["people"], "Individual lockers for belongings outside the bedrooms.", ["Units", 30, ""], "Keeping personal history matters for identity, not just utility."],
    ["f6-lounge", "Small Lounge", 1.1, "seats", ["people"], "Informal gathering corner for the residential block.", ["Seats", 10, ""], "Small social spaces prevent isolation between floors."],
  ],
  7: [
    ["f7-b1", "Bedroom 1", 0.8, "bunks", ["people", "air"], "Private quarters for a resident or family unit.", ["Occupancy", 2, "people"], "Residential capacity is split across two floors for resilience."],
    ["f7-b2", "Bedroom 2", 0.8, "bunks", ["people", "air"], "Private quarters with personal storage.", ["Occupancy", 2, "people"], "Two blocks allow one floor to be serviced without displacing everyone."],
    ["f7-b3", "Bedroom 3", 0.8, "bunks", ["people", "air"], "Private quarters with personal storage.", ["Occupancy", 1, "people"], "Distributing people limits the impact of a local fault."],
    ["f7-b4", "Bedroom 4", 0.8, "bunks", ["people", "air"], "Private quarters with personal storage.", ["Occupancy", 2, "people"], "Room assignments can change as the community changes."],
    ["f7-b5", "Bedroom 5", 0.8, "bunks", ["people", "air"], "Private quarters with personal storage.", ["Occupancy", 1, "people"], "Reserve rooms cover illness and isolation needs."],
    ["f7-b6", "Bedroom 6", 0.8, "bunks", ["people", "air"], "Private quarters with personal storage.", ["Occupancy", 2, "people"], "Ventilation reaches every room independently."],
    ["f7-b7", "Bedroom 7", 0.8, "bunks", ["people", "air"], "Private quarters with personal storage.", ["Occupancy", 0, "people"], "Empty rooms are the buffer toward the 30-person capacity."],
    ["f7-b8", "Bedroom 8", 0.8, "bunks", ["people", "air"], "Private quarters with personal storage.", ["Occupancy", 0, "people"], "Planning below capacity keeps the shelter adaptable."],
    ["f7-laundry", "Laundry", 1, "machines", ["water", "power"], "Second laundry serving Residential B.", ["Loads / day", 6, ""], "Duplicated services avoid queues and single points of failure."],
    ["f7-bath", "Shared Bathrooms", 1.1, "shower", ["water", "waste"], "Shared sanitary block for Residential B.", ["Availability", 100, "%"], "Water demand from these rooms shapes the whole water plan."],
    ["f7-store", "Personal Storage", 0.9, "lockers", ["people"], "Individual lockers for the second residential block.", ["Units", 30, ""], "Orderly storage keeps corridors clear for emergencies."],
    ["f7-lounge", "Small Lounge", 1.1, "seats", ["people"], "Informal gathering corner for Residential B.", ["Seats", 10, ""], "Neighbourhood-scale spaces build everyday trust."],
  ],
  8: [
    ["f8-prayer", "Prayer / Quiet Room", 1, "seats", ["people"], "Silent multi-faith space for reflection.", ["Capacity", 12, ""], "Meaning and ritual sustain people through long confinement."],
    ["f8-gym", "Gym", 1.1, "gym", ["people", "power"], "Exercise area with resistance and cardio equipment.", ["Sessions / day", 18, ""], "Physical activity underground protects both health and mood."],
    ["f8-game", "Game Room", 1, "seats", ["people", "power"], "Table games and play space for all ages.", ["Capacity", 14, ""], "Play is how children stay children during an emergency."],
    ["f8-bath", "Bathrooms", 0.85, "shower", ["water", "waste"], "Sanitary facilities serving the community floor.", ["Availability", 100, "%"], "High-traffic floors need their own sanitary capacity."],
    ["f8-common", "Common Area", 1.3, "seats", ["people"], "Central gathering space for meetings and announcements.", ["Capacity", 30, ""], "Shared decisions need a room where everyone fits."],
    ["f8-theater", "Mini Theater", 1.1, "screens", ["people", "power"], "Small screening room for film, briefings and lessons.", ["Seats", 20, ""], "Shared stories are a low-cost, high-value morale system."],
    ["f8-dining", "Dining Area", 1.2, "seats", ["food", "people"], "Communal tables where the community eats together.", ["Seats", 28, ""], "Eating together is the strongest daily community ritual."],
    ["f8-kitchen", "Kitchen", 1.2, "kitchen", ["food", "water", "power", "waste"], "Preparation and cooking for the whole community.", ["Meals / day", 72, ""], "The kitchen is where water, power and food all converge."],
    ["f8-park", "Mini Indoor Park", 1.3, "park", ["people", "air", "water"], "Planted green space with seating and daylight-spectrum lighting.", ["Plants", 120, ""], "Greenery measurably improves well-being in enclosed environments."],
  ],
  9: [
    ["f9-guest", "Sleeping / Guest Quarters", 1.1, "bunks", ["people", "air"], "Short-stay rooms for guests, visitors or night staff.", ["Beds", 6, ""], "Flexible space lets the community host and help others."],
    ["f9-conference", "Conference Room", 1.1, "desks", ["comms", "power"], "Planning room for coordination and community councils.", ["Seats", 14, ""], "Governance needs a dedicated place to happen."],
    ["f9-bath", "Bathroom", 0.75, "shower", ["water", "waste"], "Sanitary facilities for the education floor.", ["Availability", 100, "%"], "Every occupied floor is self-sufficient for basic needs."],
    ["f9-lab", "Computer Lab", 1.15, "servers", ["comms", "power"], "Workstations linked to the Floor 3 database.", ["Stations", 10, ""], "Local knowledge access replaces the open internet."],
    ["f9-library", "Library", 1.15, "cabinets", ["people"], "Printed archive and reading space.", ["Volumes", 2400, ""], "Paper keeps working during a total power failure."],
    ["f9-classroom", "Classroom", 1.15, "desks", ["people", "power"], "Teaching space for children and adult training.", ["Students", 9, ""], "Education is how a community plans past the emergency."],
    ["f9-art", "Art Room", 1, "desks", ["people"], "Studio for drawing, craft and making.", ["Stations", 8, ""], "Creative work is a proven outlet for stress."],
    ["f9-music", "Music Room", 1, "seats", ["people"], "Acoustically separated room for playing and practice.", ["Instruments", 7, ""], "Sound needs its own room so it stays a joy, not a nuisance."],
  ],
  10: [
    ["f10-drainage", "Drainage System", 1.1, "pumps", ["waste", "water", "power"], "Collects run-off and greywater from the floors above.", ["Flow", 84, "%"], "Water always ends up somewhere; drainage decides where."],
    ["f10-backup", "Backup Generators", 1.2, "machines", ["power"], "Standby generation that carries critical loads if main power fails.", ["Reserve", 90, "%"], "The moment main power stops, this room defines what survives."],
    ["f10-firstaid", "First-Aid Room", 0.95, "medbed", ["medical"], "Immediate care point for the technical floor.", ["Kits", 12, ""], "Care located where work happens shortens response time."],
    ["f10-segregation", "Waste Segregation", 1.1, "cabinets", ["waste"], "Sorting point separating organic, recyclable and residual waste.", ["Sorted", 78, "%"], "Sorting at the source is what makes every later step possible."],
    ["f10-digestion", "Anaerobic Digestion", 1.15, "tanks", ["waste", "power", "food"], "Conceptual biological breakdown of organic waste producing biogas.", ["Load", 68, "%"], "Yesterday's food waste conceptually becomes tomorrow's cooking energy."],
    ["f10-wastewater", "Wastewater Treatment", 1.2, "tanks", ["waste", "water"], "Multi-stage treatment before reuse or controlled discharge.", ["Throughput", 81, "%"], "Treated water re-entering the loop is what extends the survival horizon."],
    ["f10-recycling", "Recycling / Processing", 1.1, "machines", ["waste", "power"], "Reprocessing of plastics, metals and textiles into usable stock.", ["Recovered", 62, "%"], "With no deliveries arriving, materials must circulate internally."],
    ["f10-utility", "Utility Maintenance", 1, "lockers", ["power", "water"], "Workshop supporting all technical systems in the shelter.", ["Tasks open", 7, ""], "Maintenance is the invisible work that keeps day 300 like day 3."],
  ],
};

export const ROOMS: RoomDef[] = Object.entries(RAW).flatMap(([floor, list]) =>
  list.map((r) => ({
    id: r[0],
    name: r[1],
    floor: Number(floor),
    span: r[2],
    fixture: r[3],
    systems: r[4],
    purpose: r[5],
    metricLabel: r[6][0],
    metricBase: r[6][1],
    metricUnit: r[6][2],
    why: r[7],
  })),
);

export const roomsByFloor = (floor: number) => ROOMS.filter((r) => r.floor === floor);
export const roomById = (id: string) => ROOMS.find((r) => r.id === id);
